// <auto-generated />
using FashionStoreEntity.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FashionStoreEntity.Migrations
{
    [DbContext(typeof(FashionStoreEntityContext))]
    [Migration("20210315164406_FashionStore")]
    partial class FashionStore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FashionStoreEntity.DataClass.Contact", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Message");

                    b.Property<string>("Name");

                    b.HasKey("id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("FashionStoreEntity.DataClass.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Price");

                    b.Property<string>("Qty");

                    b.HasKey("id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("FashionStoreEntity.DataClass.Sale", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Bill");

                    b.Property<string>("Billdate");

                    b.Property<string>("Mobile");

                    b.Property<string>("Name");

                    b.Property<string>("Product");

                    b.HasKey("id");

                    b.ToTable("Sale");
                });
#pragma warning restore 612, 618
        }
    }
}
